#!/usr/bin/env bash
#This script will display numbers 1-100, displaying FizzBuzz when the number is a multiple of 3 and 5, Fizz when the number is a multiple of 3, and Buzz when the number is a multiple of 5.

for (( i=1; i < 101; i++ ))
do
if (( i % 15 == 0 )); then
echo "FizzBuzz"
elif (( i % 3 == 0 )); then
echo "Fizz"
elif (( i % 5 == 0 )); then
echo "Buzz"
else
echo "$i"
fi
done
