#!/usr/bin/env bash
#This cript prints "Best School" ten times, "bad luck" on the 4th, and "good luck" on the 8th

i=1
while [ "$i" -le 10 ]
do
if [ "$i" -eq 4 ]; then
elif [ "$i" -eq 8 ]; then
echo "good luck"
else
echo "Best School"
fi
(( i** ))
done